// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"www.ivtlinfoview.com/infotax/infotax-backend/app/config"
	"www.ivtlinfoview.com/infotax/infotax-backend/app/external/persistence/mysql"
	"www.ivtlinfoview.com/infotax/infotax-backend/app/usecase/student"
	"www.ivtlinfoview.com/infotax/infotax-backend/app/usecase/user"
)

// Injectors from wire.go:

func InjectedUserLoginDetailUseCase(ctx context.Context) user.UseCaser {
	configConfig := config.ParseConfig()
	db := config.NewDB(configConfig)
	userLoginDetailRepository := mysql.NewUserLoginDetailRepository(db)
	useCaser := user.NewUseCase(userLoginDetailRepository)
	return useCaser
}

func InjectedStudentDetailUseCase(ctx context.Context) student.UseCaser {
	configConfig := config.ParseConfig()
	db := config.NewDB(configConfig)
	studentDetailRepository := mysql.NewStudentDetailRepository(db)
	useCaser := student.NewUseCase(studentDetailRepository)
	return useCaser
}
